public class AddingSysout{
  public void printStmt(){
  System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
    System.out.println("New Issue");
  }
}
